{
 "title": "VerneMQ Dashboard",
 "tags": [
  "prometheus",
  "mqtt"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(socket_open) - sum(socket_close))"
    }
   ]
  },
  {
   "title": "Queues Processes",
   "type": "singlestat",
   "description": "This is the current total of living queues (started queue processes). These queues might be in an online or an offline state (ie. belong to an online or offline client).",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(queue_processes)" }
   ]
  },
  {
   "title": "VerneMQ Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "sum(system_wallclock)" }
   ]
  },
  {
   "title": "Erlang VM Utilization",
   "type": "singlestat",
   "description": "VerneMQ Broker average Erlang Scheduler utilization.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "sum(system_utilization)" }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_connect_received[30s]))",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(rate(mqtt_disconnect_received[30s]))",
     "legendFormat": "Disconnections"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 } },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Message Rate",
   "type": "graph",
   "description": "Rate of received MQTT PUBLISH frames by the broker over",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[30s]))",
     "legendFormat": "Received Rate"
    },
    {
     "expr": "sum(rate(mqtt_publish_sent[30s]))",
     "legendFormat": "Send Rate"
    }
   ]
  },
  {
   "title": "Send/sec",
   "type": "singlestat",
   "description": "Current rate per second of received MQTT PUBLISH frames by the broker.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_sent[30s]))"
    }
   ]
  },
  {
   "title": "Received (24h)",
   "type": "singlestat",
   "description": "The number of messages received in the last 24 time window.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(mqtt_publish_received[24h]))"
    }
   ]
  },
  {
   "title": "Received/sec",
   "type": "singlestat",
   "description": "Current rate per second of received MQTT PUBLISH frames by the broker.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[30s]))"
    }
   ]
  },
  {
   "title": "Sent (24h)",
   "type": "singlestat",
   "description": "The number of messages sent in the last 24 time window.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(mqtt_publish_sent[24h]))"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Router Subscriptions Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "router_subscriptions", "legendFormat": "Subscriptions Total" }
   ]
  },
  {
   "title": "Router Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "router_memory", "legendFormat": "Router Memory" }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Messages in Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(queue_message_in[1m])", "legendFormat": "In" },
    { "expr": "rate(queue_message_out[1m])", "legendFormat": "Out" },
    { "expr": "rate(queue_message_drop[1m])", "legendFormat": "Drop" },
    {
     "expr": "rate(queue_message_unhandled[1m])",
     "legendFormat": "Unhandled"
    }
   ]
  },
  {
   "title": "Queue Setup and Teardown Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(queue_setup[60s])", "legendFormat": "Queue Setup" },
    { "expr": "rate(queue_teardown[60s])", "legendFormat": "Queue Teardown" }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(bytes_received[30s])", "legendFormat": "In" },
    { "expr": "rate(bytes_sent[30s])", "legendFormat": "Out" }
   ]
  },
  {
   "title": "Erlang VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Erlang Scheduler Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "system_utilization", "legendFormat": "System Utilization" }
     ]
    },
    {
     "title": "System Reductions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      { "expr": "rate(system_reductions[30s])", "legendFormat": "System Reductions" }
     ]
    },
    {
     "title": "Erlang Scheduler Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "system_utilization_scheduler_1", "legendFormat": "Scheduler 1" },
      { "expr": "system_utilization_scheduler_2", "legendFormat": "Scheduler 2" },
      { "expr": "system_utilization_scheduler_3", "legendFormat": "Scheduler 3" },
      { "expr": "system_utilization_scheduler_4", "legendFormat": "Scheduler 4" }
     ]
    },
    {
     "title": "System IO",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      { "expr": "rate(system_io_in[30s])", "legendFormat": "System IO IN" },
      { "expr": "rate(system_io_out[30s])", "legendFormat": "System IO OUT" }
     ]
    }
   ]
  },
  { "title": "TCP Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Sockets",
   "type": "graph",
   "description": "Rate of socket open, close and error",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(socket_open[30s])", "legendFormat": "Open" },
    { "expr": "rate(socket_close[30s])", "legendFormat": "Close" },
    { "expr": "rate(socket_error[30s])", "legendFormat": "Error" }
   ]
  },
  {
   "title": "Node to Cluster Communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Communication",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      { "expr": "rate(cluster_bytes_sent[30s])", "legendFormat": "Cluster Bytes Sent" },
      {
       "expr": "rate(cluster_bytes_received[30s])",
       "legendFormat": "Cluster Bytes Received"
      },
      {
       "expr": "rate(cluster_bytes_dropped[30s])",
       "legendFormat": "Cluster Bytes Dropped"
      }
     ]
    }
   ]
  },
  { "title": "MQTT CONNACK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "MQTT CONNACK",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (return_code) (\n  rate(mqtt_connack_sent{return_code=\"success\"}[30s])\n)",
     "legendFormat": "MQTT CONNACK Success"
    }
   ]
  },
  {
   "title": "MQTT CONNACK Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (return_code) ((increase(mqtt_connack_sent{return_code=\"bad_username_or_password\"}[30s]))) ",
     "legendFormat": "Bad Username or Password"
    },
    {
     "expr": "sum by (return_code) ((increase(mqtt_connack_sent{return_code=\"not_authorized\"}[30s])))",
     "legendFormat": "Not Authorized"
    },
    {
     "expr": "sum by (return_code) ((increase(mqtt_connack_sent{return_code=\"client_identifier_not_valid\"}[30s]))) ",
     "legendFormat": "Client ID Not Valid"
    },
    {
     "expr": "sum by (return_code) ((increase(mqtt_connack_sent{return_code=\"server_unavailable\"}[30s])))  ",
     "legendFormat": "Server Unavailable"
    },
    {
     "expr": "sum by (return_code) ((increase(mqtt_connack_sent{return_code=\"unsupported_protocol_version\"}[30s])))  ",
     "legendFormat": "Unacceptable Protocol"
    }
   ]
  },
  { "title": "MQTT PUBLISH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "QOS 0,1,2: PUBLISH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[30s]))",
     "legendFormat": "PUBLISH Received"
    },
    {
     "expr": "sum(rate(mqtt_publish_sent[30s]))",
     "legendFormat": "PUBLISH Sent"
    }
   ]
  },
  {
   "title": "QOS 0,1,2: PUBLISH Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mqtt_publish_auth_error[30s]))",
     "legendFormat": "PUBLISH Auth Error"
    },
    {
     "expr": "sum(increase(mqtt_publish_error[30s]))",
     "legendFormat": "PUBLISH Error"
    }
   ]
  },
  {
   "title": "QOS 1: PUBACK Received, Sent & Invalid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_puback_received[30s]))",
     "legendFormat": "PUBACK Received"
    },
    {
     "expr": "sum(rate(mqtt_puback_sent[30s]))",
     "legendFormat": "PUBACK Sent"
    },
    {
     "expr": "sum(rate(mqtt_puback_invalid_error[30s]))",
     "legendFormat": "PUBACK Invalid"
    }
   ]
  },
  {
   "title": "QOS 2: PUBREC Received, Sent & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_pubrec_received[30s]))",
     "legendFormat": "PUBREC Received"
    },
    {
     "expr": "sum(rate(mqtt_pubrec_sent[30s]))",
     "legendFormat": "PUBREC Sent"
    },
    {
     "expr": "sum(rate(mqtt_pubrec_invalid_error[30s]))",
     "legendFormat": "PUBREC Invalid"
    }
   ]
  },
  {
   "title": "QOS 2: PUBREL Received & Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_pubrel_received[30s]))",
     "legendFormat": "PUBREL Received"
    },
    {
     "expr": "sum(rate(mqtt_pubrel_sent[30s]))",
     "legendFormat": "PUBREL Sent"
    }
   ]
  },
  {
   "title": "QOS 2: PUBCOMP Received, Sent & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_pubcomp_received[30s]))",
     "legendFormat": "PUBCOMP Received"
    },
    {
     "expr": "sum(rate(mqtt_pubcomp_sent[30s]))",
     "legendFormat": "PUBCOMP Sent"
    },
    {
     "expr": "sum(rate(mqtt_pubcomp_invalid_error[30s]))",
     "legendFormat": "PUBCOMP Invalid"
    }
   ]
  },
  {
   "title": "MQTT PING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "PINGREQ & PINGRESP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mqtt_pingreq_received[30s])",
       "legendFormat": "PINGREQ Received"
      },
      { "expr": "rate(mqtt_pingresp_sent[30s])", "legendFormat": "PINGRESP Sent" }
     ]
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Clients",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "client_expired", "legendFormat": "Expired Clients" }
     ]
    },
    {
     "title": "Invalid Message Size Error",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mqtt_invalid_msg_size_error[30s])",
       "legendFormat": "Invalid Message Size Error"
      }
     ]
    }
   ]
  }
 ]
}